apiVersion: v1
kind: Service
metadata:
  name: webnodb-service
  namespace: pliu
spec:
  selector:
    app: webnodb
  ports:
  - protocol: TCP
    port: {{ .Values.service.webnodb.port }}
    targetPort: 5000
  type: {{ .Values.service.webnodb.type }}
